### PR TITLE
Use walker

### PR DESCRIPTION
**Pull request by mattn**
filepath.Walk is bits slow since it call os.Stat for each files. This pull-request use github.com/saracen/walker instead.

```
$ ghq list | wc -l
2838
```

Before
```
real    3.537
system  2.652
user    0.608
```

After
```
real    1.054
system  2.043
user    0.374
```

### CODE REVIEW

**Comment by mattn** [comment]
Hmm, I changed behavior for permission error while walking directories. saracen/walker stop walking when non-permitted directory found. If you are okay, please merge this.

**Comment by Songmu** [comment]
Hmm, unfortunately when this is merged, the issue #173 will recur.

I also want to solve the issue #187, so I can't merge this.

**Comment by mattn** [comment]
How about copying codes of fastwalk ?

**Comment by Songmu** [comment]
That's a good idea, but before that, we should make a suggestion to saracen/walker that it can do handle unpermitted files.

Also, even if we'll use fastwalk, it's not a good idea to have source code in this repository, but it is better you fork it and utilize it in it.

**Pull request merged**
