### PR TITLE
Add ghq.findVcs for speedup of ghq list

### PR DESCRIPTION
**Pull request by autopp**
`ghq list` checks all supported VCS content in string length order.
This causes `ghq list` to be slow for users who only use certain VCSs (Especially for git and/or mercurial only).

To solve this, I added a new configuration value `ghq.findVcs`.
If nothing is set, it works as before (See README.adoc changes for details.).

In my envrionment (git repositories only), this reduce about 200 - 300ms.

Before (fe5ca05)
```
$ time ghq list >/dev/null

real    0m0.844s
user    0m0.786s
sys     0m1.885s
```

After (2d50dcd and `git config --global ghq.findVcs git`)
```
$ time ghq list >/dev/null

real    0m0.554s
user    0m0.580s
sys     0m1.096s
```

If the name `findVcs` is not good, please give me a good idea.

### CODE REVIEW

**Comment by KageShiron** [comment]
os.stat is a performance bottleneck in windows. So this is very effective in windows!

image

```powershell
<# Before #>
PS> Measure-Command { ./ghq list } | Select-Object -Property TotalSeconds

TotalSeconds
------------
   1.8705152

<# After #>
PS>  Measure-Command { ./ghq list } | Select-Object -Property TotalSeconds

TotalSeconds
------------
   0.8143256
```

**Comment by Songmu** [comment]
Thanks for the request!

What is worrisome about this pull request is that if there is a repository with a deep directory structure that is not specified VCS from the `ghq list`, it will slow down the `ghq list` or not. See #115.

Also, the `--vcs` option already exists in` ghq list`, so I think that it is better to optimize it first than to add the `ghq.findVcs` configuration.

**Comment by Songmu** [comment]
Deep directory problems may be solved by adding options such as "--max-depth". (You don't need to add it with this pull request)

So, how about extending the `--vcs` option based on this pull request?

**Comment by autopp** [comment]
@Songmu Thank you for review.
Surely I was initially thinking about using the `--vcs` option, but switched to `ghq.findVcs` to account for deep directory problems. `--max-depth` certainly seems to solve this.
I'll try optimizing the `--vcs` option in another branch.

BTW, how about the initial values of `--vcs` and` --max-depth` can be specified by environment variables or `git config`?

**Comment by autopp** [comment]
@Songmu I created #205 that optimize `--vcs` option.

**Comment by autopp** [comment]
> BTW, how about the initial values of `--vcs` and` --max-depth` can be specified by environment variables or `git config`?
As my mind has changed, I withdraw this.

**Pull request closed without merging**
