### PR TITLE
When there is no slash in the argument, complement URL as $USER/repo

### PR DESCRIPTION
**Pull request by b4b4r07**
**FEATURE REQUEST**:

When the URL is most omitted, I want *ghq(1)* to regard it as `$USER` instead of `repo`

Now, completion as `my-repo/my-repo`

```console
$ ghq get my-repo
     clone https://github.com/my-repo/my-repo -> /Users/b4b4r07/src/github.com/my-repo/my-repo
       git clone https://github.com/my-repo/my-repo /Users/b4b4r07/src/github.com/my-repo/my-repo
Cloning into '/Users/b4b4r07/src/github.com/my-repo/my-repo'...
remote: Repository not found.
fatal: repository 'https://github.com/my-repo/my-repo/' not found
     error /usr/local/bin/git: exit status 128
```

After merging this patch,

```console
$ ./ghq get my-repo
     clone https://github.com/b4b4r07/my-repo -> /Users/b4b4r07/src/github.com/b4b4r07/my-repo
       git clone https://github.com/b4b4r07/my-repo /Users/b4b4r07/src/github.com/b4b4r07/my-repo
Cloning into '/Users/b4b4r07/src/github.com/b4b4r07/my-repo'...
remote: Counting objects: 3, done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 3
Unpacking objects: 100% (3/3), done.
```

As a use case, it would be nice to be regarded as `$USER`! What do you think?

### CODE REVIEW

**Comment by syohex** [comment]
On Windows,  user name environment variable is `USERNAME`, not `USER`.

**Comment by b4b4r07** [comment]
Oh my bad, thanks. Ill fix that

**Comment by syohex** [comment]
I suppose it is better to add `ghq.user`(or `ghq.github.user`) git config variable other than `USER` and `USERNAME` environment variables too. Because username does not necessarily correspond to github account. For example, PC supplied by company.

**Comment by b4b4r07** [comment]
@all ping

**Comment by motemen** [comment]
Thank you, I like this change.

Maybe looking for `GITHUB_USER` environment variable before falling back to `USER` would be nice, which is explicity named.

**Comment by b4b4r07** [comment]
@motemen Thanks you for the suggestion, modified and squashed. Please review this change.

**Comment by motemen** [comment]
LGTM, thanks!

**Pull request merged**
