### PR TITLE
Github relative

### PR DESCRIPTION
**Pull request by mattn**
When here is `/path/to/ghq/root/github.com/motemen` and do `ghq get git-pr-release`, `github.com/motemen/git-pr-release` should be expected repository name.

### CODE REVIEW

**Comment by motemen** [comment]
Sorry for taking such long time for response.

Currently ghq is not cwd-sensitive, and this PR is breaking current behavior of fetching `https://github.com/foo/foo` on `ghq get foo`. And I'd like to preserve ghq's cwd-insensitivity for simplicity as of now.

What if changing the spec to `ghq get ./foo` not `ghq get foo`, which starts with relative path syntax and kind of obvious as it shows that the user is concious of current directory?

**Comment by mattn** [comment]
But your README.md says:
```
'ghq' get [-u] [-p] (<repository URL> | <user>/<project> | <project>)
```

**Comment by motemen** [comment]
I think you mean `ghq get <project>` part. Yes it does, but it is an abbreviation of `github.com/<project>/<project>` and not aware of current directory.

**Comment by motemen** [comment]
Finally merged it, Thank you and sorry such a late merge :pray:

**Comment by mattn** [comment]
No Problem :+1:

**Pull request merged**
