### PR TITLE
Support bazaar

### PR DESCRIPTION
**Pull request by shigemk2**
## Config

```sh
[ghq]
    vcs = bazaar
```

## Examples

```sh
$ ghq get https://launchpad.net/terminator
     clone https://launchpad.net/terminator -> /path/to/launchpad.net/terminator
       bzr branch https://launchpad.net/terminator /path/to/launchpad.net/terminator
Branched 1779 revisions.
$ ghq get -u https://launchpad.net/terminator
    update /path/to/launchpad.net/terminator
       bzr pull
Using saved parent location: http://bazaar.launchpad.net/~gnome-terminator/terminator/gtk3/
No revisions or tags to pull.
```

### CODE REVIEW

**Comment by shigemk2** [comment]
@motemen Please review this PR 😄

**Comment by motemen** [comment]
Thanks. I'm not familier with Bazaar, and I am slightly confused about that there are two different ways (`checkout` and `branch`) to clone repositories. Is there a "default" way to clone repositories? I'd like to choose one as default, so that we can use `vcs = bazaar` for default clone strategy.

Seeing some docs (eg. http://doc.bazaar.canonical.com/migration/en/survival/bzr-for-git-users.html), `bzr branch` seems suitable to be a default way for cloning in Bazaar.

**Comment by Songmu** [comment]
It is a good idea to support bazzar.
I agree with motemen and we should be able to specify VCS simply by bazzar or bzr (similar to go get).

The feature of branch specification may be considered in the future as a unified function of ghq overall.

How about it ? @shigemk2

**Comment by shigemk2** [comment]
@Songmu @motemen 

I am not sure which `bzr branch` or `bzr checkout` is "default" way because I am not familiar with Bazaar neither.

But I agree with `vcs = bazaar` as "default" way.

**Comment by Songmu** [comment]
I'm also not familiar with bazzar, but the behavior of "go get" will be helpful for you.

**Comment by shigemk2** [comment]
@Songmu 
I changed `bzr branch` when executing `ghq get`. Please review this PR again.

**Comment by Songmu** [comment]
Great! Thank you.

**Comment by shigemk2** [comment]
You are welcome!!

**Pull request merged**
